# https://rust-lang.github.io/rustfmt/?version=master
hard_tabs = true
max_width = 110
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true

use_field_init_shorthand = true
# trailing_comma = "Never"

skip_macro_invocations = ["*"]
format_generated_files = false
single_line_if_else_max_width = 0
format_strings = false

disable_all_formatting = true
